import { productCategories } from "@/content/store";
import { company, contactLinks } from "@/content/company";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";
import { ButtonLink } from "@/components/ui/ButtonLink";
import { MediaFrame } from "@/components/ui/MediaFrame";
import { SectionHeader } from "@/components/ui/SectionHeader";
import { Icon } from "@/components/ui/Icon";
import { ContactForm } from "@/components/forms/ContactForm";

export function StorePage() {
  return <main id="main-content">
    <Breadcrumbs items={[{ name: "Etusivu", href: "/" }, { name: "Myymälä", href: "/myymala" }]}/>
    <section className="service-hero"><div className="container service-hero__layout"><div className="service-hero__copy"><p className="eyebrow"><span aria-hidden="true"/>Myymälä Ullanlinnassa</p><h1>Sähkö- ja valaisintarvikemyymälä Ullanlinnassa</h1><p className="hero-lead">Pietarinkadun myymälästä voit tiedustella valaisimia, polttimoita ja muita valonlähteitä, johtoja, varaosia sekä muita sähkötarvikkeita.</p><div className="notice-card"><strong>Saatavuus kannattaa varmistaa</strong><p>Verkkosivun sisältö ei kuvaa reaaliaikaista myymäläsaatavuutta.</p></div><div className="button-row"><ButtonLink href="#tuotetiedustelu">Kysy saatavuudesta</ButtonLink><ButtonLink href={contactLinks.directions} external variant="secondary" icon="arrow">Avaa reittiohje</ButtonLink></div></div><MediaFrame priority requirement="Ajantasainen myymälän sisäkuva ilman vanhoja yhteystietoja." ratio="4/3"/></div></section>
    <section className="section"><div className="container"><div className="store-contact-strip"><span><Icon name="pin"/><strong>{company.address.street}</strong> {company.address.postalCode} {company.address.city}</span><span><Icon name="clock"/><strong>{company.openingHours.display}</strong></span><a href={contactLinks.phone}><Icon name="phone"/><strong>{company.phoneDisplay}</strong></a></div><SectionHeader eyebrow="Valikoima" title="Mitä myymälästä voi tiedustella?" lead="Tuoteryhmät ovat pysyviä sisältöjä. Yksittäisten tuotteiden saatavuus voi muuttua."/><div id="valaisimet-ja-tarvikkeet" className="category-grid">{productCategories.map((category, index) => <article key={category.id} id={category.id}><span>{String(index + 1).padStart(2, "0")}</span><Icon name={category.id === "second-hand-valaisimet" ? "store" : category.id === "varaosat" ? "wrench" : "bulb"}/><h2>{category.title}</h2><p>{category.text}</p><a href="#tuotetiedustelu">Tiedustele tuotetta <Icon name="arrow"/></a></article>)}</div></div></section>
    <section className="section section--secondary"><div className="container split-layout split-layout--media-first"><div className="feature-copy"><SectionHeader eyebrow="Asiointiohje" title="Ota mukaan kuva, mitat ja merkinnät"/><p>Sopivan osan tai valonlähteen tunnistamista helpottavat kuva vanhasta osasta, mitat, kannan tai liitännän kuva ja valaisimessa näkyvät merkinnät.</p></div><MediaFrame requirement="Todellisia myymälän tuotteita ja varaosia ryhmiteltynä selkeästi." ratio="16/10"/></div></section>
    <section className="section"><div className="container"><SectionHeader eyebrow="Valaisinpalvelut" title="Tarvitsetko osan lisäksi korjausta?"/><div className="related-grid"><ButtonLink href="/valaisimien-korjaus" variant="secondary" icon="arrow">Valaisimen korjaus</ButtonLink><ButtonLink href="/valaisimen-johdon-vaihto" variant="secondary" icon="arrow">Valaisimen johdon vaihto</ButtonLink><ButtonLink href="/vanhan-valaisimen-sahkoistys" variant="secondary" icon="arrow">Vanhan valaisimen sähköistys</ButtonLink></div></div></section>
    <section id="tuotetiedustelu" className="contact-section"><div className="container contact-layout"><div className="contact-copy"><SectionHeader eyebrow="Tuotetiedustelu" title="Kysy ennen myymäläkäyntiä"/><p>Kerro, mitä tuotetta, varaosaa tai valaisinta etsit. Liitä kuva, jos mahdollista.</p></div><div className="contact-card"><ContactForm defaultTopic="product-enquiry"/></div></div></section>
  </main>;
}
