export type SeoPageKey = "home" | "electrical" | "lighting" | "lampRepair" | "business" | "store" | "about" | "contact" | "faq" | "privacy" | "cookies" | "accessibility" | "thankYou";
export type SeoPage = { key: SeoPageKey; path: `/${string}` | "/"; title: string; description: string; breadcrumbLabel: string; indexable: boolean; includeInSitemap: boolean };
const faqEnabled = process.env.NEXT_PUBLIC_ENABLE_FAQ_PAGE === "true";
const legalApproved = process.env.NEXT_PUBLIC_LEGAL_CONTENT_APPROVED === "true";
export const seoPages: Record<SeoPageKey, SeoPage> = {
  home: { key: "home", path: "/", title: "Ullanlinnan Sähkö Oy | Sähkö- ja valaisinpalvelut Helsingissä", description: "Sähköasennukset, sähkövikojen selvitys, valaisinasennukset, valaisimien korjaus ja myymäläpalvelu Helsingissä.", breadcrumbLabel: "Etusivu", indexable: true, includeInSitemap: true },
  electrical: { key: "electrical", path: "/sahkoasennukset-ja-vikakorjaukset", title: "Sähköasennukset ja vikakorjaukset Helsingissä | Ullanlinnan Sähkö", description: "Sähköasennuksia sekä sähkövikojen selvitystä ja korjausta Helsingissä. Kerro työn tai vian lähtötiedot ja ota yhteyttä.", breadcrumbLabel: "Sähköasennukset ja vikakorjaukset", indexable: true, includeInSitemap: true },
  lighting: { key: "lighting", path: "/valaistus-ja-valaisinasennukset", title: "Valaistus ja valaisinasennukset Helsingissä | Ullanlinnan Sähkö", description: "Valaisinasennuksia ja valaistukseen liittyviä sähkötöitä Helsingissä kotitalouksille, taloyhtiöille ja yrityksille.", breadcrumbLabel: "Valaistus ja valaisinasennukset", indexable: true, includeInSitemap: true },
  lampRepair: { key: "lampRepair", path: "/valaisimien-korjaus", title: "Valaisimien korjaus Helsingissä | Ullanlinnan Sähkö", description: "Kysy valaisimen korjattavuudesta. Korjaus arvioidaan rakenteen, kunnon, turvallisuuden ja varaosien saatavuuden perusteella.", breadcrumbLabel: "Valaisimien korjaus", indexable: true, includeInSitemap: true },
  business: { key: "business", path: "/taloyhtioille-ja-yrityksille", title: "Sähkötyöt taloyhtiöille ja yrityksille | Ullanlinnan Sähkö", description: "Sähkö- ja valaistustöitä taloyhtiöille, kiinteistöjen vastuuhenkilöille ja yrityksille sovitun tarpeen mukaan.", breadcrumbLabel: "Taloyhtiöille ja yrityksille", indexable: true, includeInSitemap: true },
  store: { key: "store", path: "/myymala", title: "Valaisimet ja sähkötarvikkeet Helsingissä | Ullanlinnan Sähkö", description: "Pietarinkadun myymälästä voit tiedustella valaisimia, valonlähteitä, varaosia, johtoja, sähkötarvikkeita ja second hand -valaisimia.", breadcrumbLabel: "Myymälä", indexable: true, includeInSitemap: true },
  about: { key: "about", path: "/meista", title: "Ullanlinnan Sähkö Oy | Paikallinen sähkö- ja valaistusalan yritys", description: "Ullanlinnan Sähkö Oy yhdistää sähkötyöt, valaisimien korjauksen ja paikallisen myymäläpalvelun Helsingissä.", breadcrumbLabel: "Meistä", indexable: true, includeInSitemap: true },
  contact: { key: "contact", path: "/yhteystiedot", title: "Yhteystiedot | Ullanlinnan Sähkö Oy", description: "Ullanlinnan Sähkö Oy, Pietarinkatu 21, 00150 Helsinki. Puhelin 040 574 3094. Myymälä avoinna keskiviikkoisin klo 10–17.", breadcrumbLabel: "Yhteystiedot", indexable: true, includeInSitemap: true },
  faq: { key: "faq", path: "/usein-kysytyt-kysymykset", title: "Usein kysytyt kysymykset | Ullanlinnan Sähkö Oy", description: "Vastauksia sähkö-, valaisin-, korjaus- ja myymäläasiointia koskeviin kysymyksiin.", breadcrumbLabel: "Usein kysytyt kysymykset", indexable: faqEnabled, includeInSitemap: faqEnabled },
  privacy: { key: "privacy", path: "/tietosuojaseloste", title: "Tietosuojaseloste | Ullanlinnan Sähkö Oy", description: "Tietoa Ullanlinnan Sähkö Oy:n henkilötietojen käsittelystä.", breadcrumbLabel: "Tietosuojaseloste", indexable: legalApproved, includeInSitemap: legalApproved },
  cookies: { key: "cookies", path: "/evastekaytanto", title: "Evästekäytäntö | Ullanlinnan Sähkö Oy", description: "Tietoa Ullanlinnan Sähkö Oy:n verkkosivuston evästeistä ja evästevalinnoista.", breadcrumbLabel: "Evästekäytäntö", indexable: legalApproved, includeInSitemap: legalApproved },
  accessibility: { key: "accessibility", path: "/saavutettavuusseloste", title: "Saavutettavuusseloste | Ullanlinnan Sähkö Oy", description: "Ullanlinnan Sähkö Oy:n verkkosivuston saavutettavuuden tila ja palautekanava.", breadcrumbLabel: "Saavutettavuusseloste", indexable: legalApproved, includeInSitemap: legalApproved },
  thankYou: { key: "thankYou", path: "/kiitos", title: "Kiitos yhteydenotosta | Ullanlinnan Sähkö Oy", description: "Yhteydenotto on vastaanotettu.", breadcrumbLabel: "Kiitos yhteydenotosta", indexable: false, includeInSitemap: false }
};
export const seoPageList = Object.values(seoPages);
